"""empty message

Revision ID: 11123b65787c
Revises: c5289801e3a0
Create Date: 2022-04-10 13:51:32.461809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11123b65787c'
down_revision = 'c5289801e3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accomplishments', sa.Column('discipline', sa.String(length=140), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accomplishments', 'discipline')
    # ### end Alembic commands ###
